bot:
  # The logging level for the bot.
  # Use "DEBUG" for detailed debugging information, "INFO" for general information,
  # "WARNING" for warning messages, "ERROR" for error messages, and "CRITICAL" for critical issues.
  log_level: "INFO"  # Mudado para INFO para reduzir logs e melhorar performance

  # Create a deck code when the game starts
  load_deck: False
  auto_start_game: True
  auto_restart: True  # Novo: Auto-restart após fim da partida
  enable_gui: True

adb:
  # The IP address of your device or emulator.
  # Use 127.0.0.1 for a local emulator. If you're connecting to a physical device,
  # make sure to use the device's IP address.
  ip: "127.0.0.1"

  # The serial number of your device
  # Use adb devices to obtain it
  # Set to auto for automatic detection
  device_serial: auto

visuals:
  # show_images displays the bot's current view in a GUI.
  # save_images saves the images seen by the bot.
  # save_labels saves the images along with the labels and the bot's perspective.
  save_labels: False
  save_images: False
  show_images: True  # Enable to see what the bot is seeing

ingame:
  # The delay between actions.
  # The default is 1. For faster action execution on high-performance PCs, you can set this to 0.5.
  # For lower-performance PCs, consider using 1.25 to 1.5.
  play_action: 0.8  # Reduzido para 0.8 para ações mais rápidas

# Machine Learning Configuration
ml:
  # Enable machine learning for improved gameplay
  enabled: True
  # Path to save the trained model
  model_path: "ml_model.pkl"
  # Path to save game data for training
  data_path: "game_data.json"
  # Path to save deck analysis memory
  deck_memory_path: "deck_memory.json"
  # How often to retrain the model (in games)
  training_frequency: 5
  # Enable enemy deck analysis
  enable_deck_analysis: True
